const fs = require('fs');

const path = 'blog.json';

try {
  let data = JSON.parse(fs.readFileSync(path, 'utf8'));

  let currentId = data.blog.posts.length > 0 ? Math.max(...data.blog.posts.map(p => p.id)) : 0;
  
  const topics = ["React", "Vue", "Angular", "CSS", "HTML", "JavaScript", "TypeScript", "Node.js", "Express", "MongoDB", "Tailwind", "Next.js", "Design Systems", "Web Performance"];
  const adjectives = ["Awesome", "Modern", "Advanced", "Beginner's Guide to", "Mastering", "Understanding", "Exploring", "The Future of", "Scaling"];

  for (let i = 0; i < 50; i++) {
    currentId++;
    const topic = topics[Math.floor(Math.random() * topics.length)];
    const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
    const title = `${adj} ${topic} in 2025 - Part ${i+1}`;
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '') + `-${currentId}`;
    
    // Create random date starting from Jan 1 2025
    const dateObj = new Date(2025, 0, 1);
    dateObj.setDate(dateObj.getDate() + i);
    const dateStr = dateObj.toISOString().split('T')[0];

    const post = {
      id: currentId,
      title: title,
      slug: slug,
      content: `This is an autogenerated post about ${topic}. It covers the ${adj.toLowerCase()} aspects of developing with this technology, exploring new features, performance improvements, and best practices.\n\n` +
               `We discuss how to scale applications and improve frontend user experiences. ` +
               `Stay tuned for more updates on ${topic}!`,
      category: "Technology",
      tags: [topic, "Web Development", "2025"],
      published: true,
      date: dateStr,
      readingTime: (Math.floor(Math.random() * 8) + 3) + " min",
      views: Math.floor(Math.random() * 1000) + 10
    };
    
    data.blog.posts.push(post);
  }

  // Sort by date (descending)
  data.blog.posts.sort((a, b) => new Date(b.date) - new Date(a.date));

  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log('Successfully added 50 posts to blog.json');
} catch (err) {
  console.error('Error generating posts:', err);
}
